### PR TITLE
Fixed app crashing when BT was turned off while the app was in the background.

### LINKED ISSUE #14: App crashes when BT is turned off and the app is in the background.

### PR DESCRIPTION
**Pull request by g-ortuno**
Fixes #14

### CODE REVIEW

File: app/src/main/java/io/github/webbluetoothcg/bletestperipheral/Peripherals.java [hunk 1]
```diff
@@ -258,13 +258,16 @@ protected void onActivityResult(int requestCode, int resultCode, Intent data) {
   @Override
   protected void onStart() {
     super.onStart();
-    if (mAdvertiser != null) {
+    mGattServer = mBluetoothManager.openGattServer(this, mGattServerCallback);
+    // The user might have disabled bluetooth when the app was in the background
```
Comment (jyasskin) [inline app/src/main/java/io/github/webbluetoothcg/bletestperipheral/Peripherals.java]: Maybe "If the user disabled Bluetooth when the app was in the background, openGattServer() will return null."

(Generally remember to end comments with punctuation, so the reader knows you finished your thought.)

**Comment by jyasskin** [comment]
lgtm

File: app/src/main/java/io/github/webbluetoothcg/bletestperipheral/Peripherals.java (hunk 1 above)
Comment (g-ortuno) [inline app/src/main/java/io/github/webbluetoothcg/bletestperipheral/Peripherals.java]: Damn. Forgot about that. Done.
